using System.Collections.Generic;

namespace ShortcutDock
{
    public sealed class Strings
    {
        public string Language;
        static readonly Dictionary<string, string[]> Text = new Dictionary<string, string[]> {
            {"Title", new[]{"快捷键面板", "Shortcut panel"}},
            {"Subtitle", new[]{"食得咸鱼抵得渴", "食得咸鱼抵得渴"}},
            {"Search", new[]{"搜索快捷键、功能或备注…", "Search shortcuts, actions or notes…"}},
            {"Keys", new[]{"快捷键组合", "SHORTCUT"}},
            {"Description", new[]{"功能", "ACTION"}},
            {"Notes", new[]{"备注", "NOTES"}},
            {"EditNotes", new[]{"编辑备注", "Edit notes"}},
            {"NotesHint", new[]{"双击备注格编辑；Win + . 输入 emoji，也可直接粘贴。", "Double-click notes to edit. Use Win + . for emoji, or paste."}},
            {"Preview", new[]{"显示预览", "PREVIEW"}},
            {"PinRow", new[]{"置顶", "Pin to top"}},
            {"UnpinRow", new[]{"取消置顶", "Unpin from top"}},
            {"PanelColor", new[]{"面板颜色", "PANEL COLOR"}},
            {"PaletteBlue", new[]{"淡蓝", "Soft blue"}},
            {"PalettePink", new[]{"浅粉", "Soft pink"}},
            {"PaletteGreen", new[]{"浅绿", "Soft green"}},
            {"PaletteHint", new[]{"三种配色随外观模式调整，点击即可预览。", "Three palettes adapt to the appearance mode. Click to preview."}},
            {"FontScale", new[]{"整体字号", "TEXT SIZE"}},
            {"FontHint", new[]{"调整标题、列表、按钮及备注的字号，emoji 同步缩放。", "Resizes headings, lists, buttons and notes, including emoji."}},
            {"NotesVisible", new[]{"显示备注列", "Show notes column"}},
            {"HideNotes", new[]{"收起备注", "Hide notes"}},
            {"ShowNotes", new[]{"展开备注", "Show notes"}},
            {"ImportTxt", new[]{"导入快捷键 TXT…", "Import shortcuts TXT…"}},
            {"DownloadTemplate", new[]{"下载模板 TXT 文件…", "Save TXT template…"}},
            {"TemplateSaved", new[]{"模板 TXT 文件已保存", "TXT template saved"}},
            {"ImportTarget", new[]{"导入到", "IMPORT INTO"}},
            {"NewImportTab", new[]{"新建软件标签页", "New software tab"}},
            {"CurrentImportTab", new[]{"当前标签页：{0}", "Current tab: {0}"}},
            {"ImportPreview", new[]{"共 {0} 条；每行“快捷键@功能”。确认后追加导入。", "{0} entries; one shortcut@action per line. Confirm to append."}},
            {"ImportedTxt", new[]{"已导入 {0} 条，跳过 {1} 条相同记录。", "Imported {0} entries; skipped {1} identical entries."}},
            {"InvalidTxt", new[]{"第 {0} 行：需要“快捷键@功能”，两侧不能为空。", "Line {0}: expected non-empty shortcut@action."}},
            {"EmptyTxt", new[]{"文件中没有快捷键。", "No shortcuts in this file."}},
            {"ImportLimit", new[]{"导入后超过数量上限。", "Import exceeds the entry or tab limit."}},
            {"AddTab", new[]{"新建软件标签页", "New software tab"}},
            {"AddTabOrGroup", new[]{"新建标签页或标签组", "New tab or group"}},
            {"AddGroup", new[]{"新建标签组", "New tab group"}},
            {"GroupName", new[]{"组名称", "Group name"}},
            {"RenameGroup", new[]{"重命名标签组", "Rename group"}},
            {"DissolveGroup", new[]{"解散标签组", "Ungroup tabs"}},
            {"DissolveQuestion", new[]{"解散“{0}”？组内标签页将移回外层，快捷键保留。", "Ungroup \"{0}\"? Its tabs return to the top level; shortcuts are kept."}},
            {"GroupHint", new[]{"双击进入；长按拖动排序。拖软件标签到组中间加入，左右边缘调整顺序。", "Double-click to open; hold to reorder. Drop app tabs at the center to add them, or at either edge to reorder."}},
            {"TabOrderHint", new[]{"按住约 0.3 秒拖动；插入线表示排序，组中间高亮表示加入组。", "Hold about 0.3 s and drag. A line means reorder; a highlighted group center means move into it."}},
            {"BackToTabs", new[]{"返回外层标签页", "Back to top-level tabs"}},
            {"RemoveFromGroup", new[]{"移出标签组", "Move out of group"}},
            {"EmptyGroup", new[]{"这个组还没有标签页，点击 + 添加，或返回外层拖入标签。", "This group is empty. Use + to add a tab, or go back and drop a tab into it."}},
            {"RootEmpty", new[]{"双击标签组查看，或点击 + 新建软件标签页。", "Double-click a group to open it, or use + to create a software tab."}},
            {"LimitGroups", new[]{"最多支持 200 个标签组。", "Maximum: 200 tab groups."}},
            {"Rename", new[]{"重命名标签页", "Rename tab"}},
            {"DeleteTab", new[]{"删除标签页", "Delete tab"}},
            {"Name", new[]{"软件名称", "Software name"}},
            {"AddShortcut", new[]{"添加快捷键", "Add shortcut"}},
            {"EditShortcut", new[]{"编辑快捷键", "Edit shortcut"}},
            {"DeleteShortcut", new[]{"删除快捷键", "Delete shortcut"}},
            {"Capture", new[]{"按下组合键录入", "Press keys to record"}},
            {"Save", new[]{"保存", "Save"}}, {"Cancel", new[]{"取消", "Cancel"}},
            {"Settings", new[]{"设置", "Settings"}}, {"Appearance", new[]{"外观", "APPEARANCE"}},
            {"Glass", new[]{"磨砂玻璃", "Frosted glass"}}, {"Light", new[]{"浅色", "Light"}},
            {"Dark", new[]{"深色", "Dark"}}, {"Auto", new[]{"跟随壁纸亮度", "Follow wallpaper brightness"}},
            {"Dock", new[]{"吸附位置", "DOCK POSITION"}},
            {"Docked", new[]{"已吸附{0} · 点击外部或移开收起", "Docked {0} · click outside or leave to hide"}},
            {"Resize", new[]{"拖拉调整面板尺寸", "Drag to resize panel"}},
            {"ColumnResizeHint", new[]{"拖动表头分界调整列宽；固定时锁定调整。", "Drag a header divider to resize. Locked while pinned."}},
            {"Transparency", new[]{"面板透明度", "PANEL TRANSPARENCY"}},
            {"TransparencyHint", new[]{"只调整背景，文字保持清晰；磨砂玻璃主题可透出模糊背景。", "Adjusts the background only; text stays crisp. Frosted glass blurs the backdrop."}},
            {"Left", new[]{"左侧", "Left"}}, {"Right", new[]{"右侧", "Right"}},
            {"Top", new[]{"顶部", "Top"}}, {"Bottom", new[]{"底部", "Bottom"}},
            {"Floating", new[]{"自由悬浮", "Floating"}},
            {"Language", new[]{"界面语言", "LANGUAGE"}},
            {"Pinned", new[]{"已固定 · 保持展开 · 编辑锁定", "Pinned · stays open · editing locked"}},
            {"AutoHide", new[]{"边缘悬停展开 · 移开自动收起", "Hover edge to open · leave to hide"}},
            {"Pin", new[]{"固定并锁定编辑 / 取消固定", "Pin and lock editing / unpin"}},
            {"LockedHint", new[]{"取消固定后可编辑 · 搜索仍可用", "Unpin to edit · search remains available"}},
            {"Collapse", new[]{"立即收起", "Collapse now"}},
            {"Show", new[]{"展开面板", "Show panel"}}, {"Exit", new[]{"退出", "Exit"}},
            {"Import", new[]{"导入备份…", "Import backup…"}}, {"Export", new[]{"导出备份…", "Export backup…"}},
            {"NoRows", new[]{"没有匹配的快捷键", "No matching shortcuts"}},
            {"NoTabs", new[]{"创建一个软件标签页，开始整理。", "Create a software tab to get started."}},
            {"Count", new[]{"{0} 条快捷键", "{0} shortcuts"}},
            {"RowHint", new[]{"Shift 连选 · 长按拖动排序", "Shift-select · hold and drag to reorder"}},
            {"DragPinGroups", new[]{"置顶和普通词条请分别拖动。", "Drag pinned and unpinned entries separately."}},
            {"Drag", new[]{"拖动标题栏，靠近屏幕边缘吸附", "Drag title near a screen edge to dock"}},
            {"Error", new[]{"操作未完成", "Could not complete action"}},
            {"Invalid", new[]{"请填写所有字段。", "Please fill in all fields."}},
            {"LimitTabs", new[]{"最多支持 200 个标签页。", "Maximum: 200 tabs."}},
            {"DeleteQuestion", new[]{"删除“{0}”？此操作无法撤销。", "Delete \"{0}\"? This cannot be undone."}},
            {"ImportQuestion", new[]{"用此备份替换所有标签页和设置？当前数据会保留为 .bak。", "Replace all tabs and settings? Current data will remain in .bak."}},
            {"Saved", new[]{"已保存到本机", "Saved locally"}},
            {"Exported", new[]{"备份已导出", "Backup exported"}},
            {"RecoveredData", new[]{"数据文件损坏，已保留原文件并从备份恢复；无有效备份时使用示例。", "Damaged data preserved; restored backup or examples if no valid backup exists."}},
            {"GlassFallback", new[]{"当前系统使用透明底备用外观", "Transparent fallback on this system"}},
            {"AutoHint", new[]{"每 30 秒采样当前屏幕壁纸；读取失败时跟随系统主题。", "Samples this screen's wallpaper every 30 s; uses system theme if unavailable."}},
            {"Help", new[]{"标签页右键重命名；快捷键仅用于查阅。", "Right-click tabs to rename. Shortcuts are for reference."}}
        };
        public Strings(string language) { Language = language; }
        public string this[string key] { get { string[] pair; return Text.TryGetValue(key, out pair) ? pair[Language == "en" ? 1 : 0] : key; } }
    }
}
